version: '3.5'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env.prod
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - docker-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file:
      - ./.env.prod
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - docker-network


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - ./.env.prod
    ports:
      - '5051:80'
    depends_on:
      - db
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge